USA daily state reports (csse_covid_19_daily_reports_us)
This table contains an aggregation of each USA State level data.

File naming convention
MM-DD-YYYY.csv in UTC.

Field description

Province_State - The name of the State within the USA.

Country_Region - The name of the Country (US).

Last_Update - The most recent date the file was pushed.

Lat - Latitude.

Long_ - Longitude.

Confirmed - Aggregated case count for the state.

Deaths - Aggregated death toll for the state.

Recovered - Aggregated Recovered case count for the state.

Active - Aggregated confirmed cases that have not been resolved (Active cases = total cases - total recovered - total deaths).

FIPS - Federal Information Processing Standards code that uniquely identifies counties within the USA.

Incident_Rate - cases per 100,000 persons.

Total_Test_Results - Total number of people who have been tested.

People_Hospitalized - Total number of people hospitalized. (Nullified on Aug 31, see Issue #3083)

Case_Fatality_Ratio - Number recorded deaths * 100/ Number confirmed cases.

UID - Unique Identifier for each row entry.

ISO3 - Officially assigned country code identifiers.

Testing_Rate - Total test results per 100,000 persons. The "total test results" are equal to "Total test results (Positive + Negative)" from COVID Tracking Project.

Hospitalization_Rate - US Hospitalization Rate (%): = Total number hospitalized / Number cases. The "Total number hospitalized" is the "Hospitalized – Cumulative" count from COVID Tracking Project. The "hospitalization rate" and "Total number hospitalized" is only presented for those states which provide cumulative hospital data. (Nullified on Aug 31, see Issue #3083)

Update frequency
Once per day between 04:45 and 05:15 UTC.

In [1]:
from datetime import datetime, timedelta
import pandas as pd
import numpy as np
from datetime import datetime

Carga del archivo datos_combinados_csse_covid_19_daily_reports_us.csv en el dataframe df_daily_reports_us

In [2]:
df_daily= pd.read_csv('C:/Users/fasch/Downloads/pybooks/patri/datos_combinados_csse_covid_19_daily_reports_us.csv')

In [3]:
df_daily.tail()

,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,FIPS,...,Total_Test_Results,People_Hospitalized,Case_Fatality_Ratio,UID,ISO3,Testing_Rate,Hospitalization_Rate,Date,People_Tested,Mortality_Rate
61609,Virginia,US,2023-01-01 04:31:23,37.7693,-78.1700,2199302,22670,NaN,NaN,51.0,...,NaN,NaN,1.030782,84000051.0,USA,NaN,NaN,NaN,NaN,NaN
61610,Washington,US,2023-01-01 04:31:23,47.4009,-121.4905,1883676,15038,NaN,NaN,53.0,...,NaN,NaN,0.798333,84000053.0,USA,NaN,NaN,NaN,NaN,NaN
61611,West Virginia,US,2023-01-01 04:31:23,38.4912,-80.9545,624721,7672,NaN,NaN,54.0,...,NaN,NaN,1.228068,84000054.0,USA,NaN,NaN,NaN,NaN,NaN
61612,Wisconsin,US,2023-01-01 04:31:23,44.2685,-89.6165,1960878,15802,NaN,NaN,55.0,...,NaN,NaN,0.805863,84000055.0,USA,NaN,NaN,NaN,NaN,NaN
61613,Wyoming,US,2023-01-01 04:31:23,42.7560,-107.3025,182847,1958,NaN,NaN,56.0,...,NaN,NaN,1.070841,84000056.0,USA,NaN,NaN,NaN,NaN,NaN

Transponemos el dataframe para visualizar las variables más comodamente

In [4]:
df_daily.T

,0,1,2,3,4,5,6,7,8,9,...,61604,61605,61606,61607,61608,61609,61610,61611,61612,61613
Province_State,Alabama,Alaska,American Samoa,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,Diamond Princess,...,Tennessee,Texas,Utah,Vermont,Virgin Islands,Virginia,Washington,West Virginia,Wisconsin,Wyoming
Country_Region,US,US,US,US,US,US,US,US,US,US,...,US,US,US,US,US,US,US,US,US,US
Last_Update,2021-01-02 05:30:44,2021-01-02 05:30:44,2021-01-02 05:30:44,2021-01-02 05:30:44,2021-01-02 05:30:44,2021-01-02 05:30:44,2021-01-02 05:30:44,2021-01-02 05:30:44,2021-01-02 05:30:44,2021-01-02 05:30:44,...,2023-01-01 04:31:23,2023-01-01 04:31:23,2023-01-01 04:31:23,2023-01-01 04:31:23,2023-01-01 04:31:23,2023-01-01 04:31:23,2023-01-01 04:31:23,2023-01-01 04:31:23,2023-01-01 04:31:23,2023-01-01 04:31:23
Lat,32.3182,61.3707,-14.271,33.7298,34.9697,36.1162,39.0598,41.5978,39.3185,NaN,...,35.7478,31.0545,40.15,44.0459,18.3358,37.7693,47.4009,38.4912,44.2685,42.756
Long_,-86.9023,-152.4044,-170.132,-111.4312,-92.3731,-119.6816,-105.3111,-72.7554,-75.5071,NaN,...,-86.6923,-97.5635,-111.8624,-72.7107,-64.8963,-78.17,-121.4905,-80.9545,-89.6165,-107.3025
Confirmed,365747,47019,0,530267,229442,2434971,362438,185708,58064,49,...,2439804,8211376,1074828,148393,23781,2199302,1883676,624721,1960878,182847
Deaths,4872,206,0,9015,3711,26298,5435,5995,1065,0,...,28589,91594,5187,791,127,22670,15038,7672,15802,1958
Recovered,202137.0,7165.0,NaN,76934.0,199247.0,NaN,18102.0,9800.0,18851.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Active,158738.0,39648.0,NaN,444318.0,26484.0,NaN,314186.0,169913.0,38148.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FIPS,1.0,2.0,60.0,4.0,5.0,6.0,8.0,9.0,10.0,88888.0,...,47.0,48.0,49.0,50.0,78.0,51.0,53.0,54.0,55.0,56.0
Incident_Rate,7459.375895,6427.355802,0.0,7285.171274,7602.945718,6164.469663,5854.774381,5208.781229,5962.841099,NaN,...,35566.966078,28376.061414,33525.953865,23781.34871,22169.705784,25766.470674,24736.736288,34858.803435,33677.977286,31592.942831
Total_Test_Results,NaN,1275750.0,2140.0,5155330.0,2051488.0,33058311.0,4444206.0,4320693.0,1021582.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
People_Hospitalized,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Case_Fatality_Ratio,1.332068,0.438121,NaN,1.700087,1.617402,1.074344,1.445304,3.228186,1.834183,0.0,...,1.175703,1.115936,0.482589,0.533044,0.53404,1.030782,0.798333,1.228068,0.805863,1.070841
UID,84000001.0,84000002.0,16.0,84000004.0,84000005.0,84000006.0,84000008.0,84000009.0,84000010.0,84088888.0,...,84000047.0,84000048.0,84000049.0,84000050.0,850.0,84000051.0,84000053.0,84000054.0,84000055.0,84000056.0
ISO3,USA,USA,ASM,USA,USA,USA,USA,USA,USA,USA,...,USA,USA,USA,USA,VIR,USA,USA,USA,USA,USA
Testing_Rate,NaN,174391.185778,3846.084722,39551.860582,67979.497674,83666.03671,77173.289416,121187.803394,0.00001,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hospitalization_Rate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Date,2021-01-01,2021-01-01,2021-01-01,2021-01-01,2021-01-01,2021-01-01,2021-01-01,2021-01-01,2021-01-01,2021-01-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
People_Tested,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Mortality_Rate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df_daily.shape

(61614, 21)

In [6]:
df_daily.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61614 entries, 0 to 61613
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Province_State        61614 non-null  object
 1   Country_Region        61614 non-null  object
 2   Last_Update           61595 non-null  object
 3   Lat                   59472 non-null  float64
 4   Long_                 59472 non-null  float64
 5   Confirmed             61614 non-null  int64
 6   Deaths                61614 non-null  int64
 7   Recovered             15122 non-null  float64
 8   Active                15122 non-null  float64
 9   FIPS                  61595 non-null  float64
 10  Incident_Rate         59472 non-null  float64
 11  Total_Test_Results    36637 non-null  float64
 12  People_Hospitalized   5129 non-null   float64
 13  Case_Fatality_Ratio   49027 non-null  float64
 14  UID                   61614 non-null  float64
 15  ISO3                  61614 non-null  object
 16  Testing_Rate          45921 non-null  float64
 17  Hospitalization_Rate  5129 non-null   float64
 18  Date                  51754 non-null  object
 19  People_Tested         11816 non-null  float64
 20  Mortality_Rate        12027 non-null  float64
dtypes: float64(14), int64(2), object(5)
memory usage: 9.9+ MB

Transformamos los campos Date a tipo fecha

In [7]:
df_daily['Date']= pd.to_datetime(df_daily['Date'])

Corroboramos la conversión de los campos

In [8]:
df_daily.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61614 entries, 0 to 61613
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Province_State        61614 non-null  object
 1   Country_Region        61614 non-null  object
 2   Last_Update           61595 non-null  object
 3   Lat                   59472 non-null  float64
 4   Long_                 59472 non-null  float64
 5   Confirmed             61614 non-null  int64
 6   Deaths                61614 non-null  int64
 7   Recovered             15122 non-null  float64
 8   Active                15122 non-null  float64
 9   FIPS                  61595 non-null  float64
 10  Incident_Rate         59472 non-null  float64
 11  Total_Test_Results    36637 non-null  float64
 12  People_Hospitalized   5129 non-null   float64
 13  Case_Fatality_Ratio   49027 non-null  float64
 14  UID                   61614 non-null  float64
 15  ISO3                  61614 non-null  object
 16  Testing_Rate          45921 non-null  float64
 17  Hospitalization_Rate  5129 non-null   float64
 18  Date                  51754 non-null  datetime64[ns]
 19  People_Tested         11816 non-null  float64
 20  Mortality_Rate        12027 non-null  float64
dtypes: datetime64[ns](1), float64(14), int64(2), object(4)
memory usage: 9.9+ MB

Contamos las filas duplicadas si existen

In [9]:
df_daily.duplicated().sum()

54

Eliminamos las filas duplicadas

In [10]:
df_daily.drop_duplicates()

,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,FIPS,...,Total_Test_Results,People_Hospitalized,Case_Fatality_Ratio,UID,ISO3,Testing_Rate,Hospitalization_Rate,Date,People_Tested,Mortality_Rate
0,Alabama,US,2021-01-02 05:30:44,32.3182,-86.9023,365747,4872,202137.0,158738.0,1.0,...,NaN,NaN,1.332068,84000001.0,USA,NaN,NaN,2021-01-01,NaN,NaN
1,Alaska,US,2021-01-02 05:30:44,61.3707,-152.4044,47019,206,7165.0,39648.0,2.0,...,1275750.0,NaN,0.438121,84000002.0,USA,174391.185778,NaN,2021-01-01,NaN,NaN
2,American Samoa,US,2021-01-02 05:30:44,-14.2710,-170.1320,0,0,NaN,NaN,60.0,...,2140.0,NaN,NaN,16.0,ASM,3846.084722,NaN,2021-01-01,NaN,NaN
3,Arizona,US,2021-01-02 05:30:44,33.7298,-111.4312,530267,9015,76934.0,444318.0,4.0,...,5155330.0,NaN,1.700087,84000004.0,USA,39551.860582,NaN,2021-01-01,NaN,NaN
4,Arkansas,US,2021-01-02 05:30:44,34.9697,-92.3731,229442,3711,199247.0,26484.0,5.0,...,2051488.0,NaN,1.617402,84000005.0,USA,67979.497674,NaN,2021-01-01,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61609,Virginia,US,2023-01-01 04:31:23,37.7693,-78.1700,2199302,22670,NaN,NaN,51.0,...,NaN,NaN,1.030782,84000051.0,USA,NaN,NaN,NaT,NaN,NaN
61610,Washington,US,2023-01-01 04:31:23,47.4009,-121.4905,1883676,15038,NaN,NaN,53.0,...,NaN,NaN,0.798333,84000053.0,USA,NaN,NaN,NaT,NaN,NaN
61611,West Virginia,US,2023-01-01 04:31:23,38.4912,-80.9545,624721,7672,NaN,NaN,54.0,...,NaN,NaN,1.228068,84000054.0,USA,NaN,NaN,NaT,NaN,NaN
61612,Wisconsin,US,2023-01-01 04:31:23,44.2685,-89.6165,1960878,15802,NaN,NaN,55.0,...,NaN,NaN,0.805863,84000055.0,USA,NaN,NaN,NaT,NaN,NaN
61613,Wyoming,US,2023-01-01 04:31:23,42.7560,-107.3025,182847,1958,NaN,NaN,56.0,...,NaN,NaN,1.070841,84000056.0,USA,NaN,NaN,NaT,NaN,NaN

Contamos los valores nulos si es que existen

In [11]:
df_daily.isnull().values.sum()

374920

Exploramos en que variables existen nulos y que cantidad

In [12]:
df_daily.isnull().sum()

Province_State              0
Country_Region              0
Last_Update                19
Lat                      2142
Long_                    2142
Confirmed                   0
Deaths                      0
Recovered               46492
Active                  46492
FIPS                       19
Incident_Rate            2142
Total_Test_Results      24977
People_Hospitalized     56485
Case_Fatality_Ratio     12587
UID                         0
ISO3                        0
Testing_Rate            15693
Hospitalization_Rate    56485
Date                     9860
People_Tested           49798
Mortality_Rate          49587
dtype: int64

In [13]:
df_daily.describe().T

,count,mean,std,min,25%,50%,75%,max
Lat,59472.0,3.684009e+01,1.078948e+01,-1.427100e+01,3.459460e+01,3.906185e+01,4.236165e+01,6.137070e+01
Long_,59472.0,-8.520661e+01,4.930863e+01,-1.701322e+02,-1.011658e+02,-8.794420e+01,-7.697062e+01,1.456739e+02
Confirmed,61614.0,8.733315e+05,1.456507e+06,0.000000e+00,6.504400e+04,3.398785e+05,1.021842e+06,1.212970e+07
Deaths,61614.0,1.157868e+04,1.715115e+04,0.000000e+00,1.104000e+03,4.896000e+03,1.470300e+04,1.011590e+05
Recovered,15122.0,8.578908e+04,1.933303e+05,0.000000e+00,3.872000e+03,1.754850e+04,8.425575e+04,2.470308e+06
Active,15122.0,5.936916e+04,1.190129e+05,0.000000e+00,3.166000e+03,1.475250e+04,6.111500e+04,1.408516e+06
FIPS,61595.0,3.285102e+03,1.725006e+04,1.000000e+00,1.800000e+01,3.200000e+01,4.800000e+01,9.999900e+04
Incident_Rate,59472.0,1.491187e+04,1.131529e+04,0.000000e+00,4.123370e+03,1.232773e+04,2.549170e+04,5.892799e+04
Total_Test_Results,36637.0,1.144235e+07,2.018320e+07,1.768000e+03,1.771434e+06,4.784927e+06,1.296786e+07,1.844461e+08
People_Hospitalized,5129.0,6.151227e+03,1.379109e+04,2.000000e+00,5.580000e+02,2.014000e+03,6.001000e+03,8.999500e+04
Case_Fatality_Ratio,49027.0,1.329953e+00,5.955981e-01,0.000000e+00,1.007261e+00,1.287040e+00,1.591256e+00,8.803612e+00
UID,61614.0,7.676408e+07,2.357418e+07,1.600000e+01,8.400001e+07,8.400003e+07,8.400004e+07,8.410000e+07
Testing_Rate,45921.0,1.161119e+05,1.307875e+05,5.973514e-08,7.422100e+03,7.692253e+04,1.787269e+05,7.901759e+05
Hospitalization_Rate,5129.0,1.214389e+01,5.245396e+00,1.418440e+00,8.359942e+00,1.128209e+01,1.526824e+01,3.850119e+01
People_Tested,11816.0,1.111017e+06,2.059628e+06,3.000000e+00,1.132178e+05,4.153255e+05,1.152972e+06,1.956515e+07
Mortality_Rate,12027.0,3.322792e+00,2.487746e+00,0.000000e+00,1.667964e+00,2.850501e+00,4.473480e+00,7.037037e+01

In [14]:
df_daily.sort_values(by=['Province_State','Date'], na_position='first' ).T

,116,290,464,638,812,986,1160,1334,1508,1682,...,42299,42473,42647,42821,42995,43169,43343,43517,43691,43865
Province_State,Alabama,Alabama,Alabama,Alabama,Alabama,Alabama,Alabama,Alabama,Alabama,Alabama,...,Wyoming,Wyoming,Wyoming,Wyoming,Wyoming,Wyoming,Wyoming,Wyoming,Wyoming,Wyoming
Country_Region,US,US,US,US,US,US,US,US,US,US,...,US,US,US,US,US,US,US,US,US,US
Last_Update,2023-01-02 04:31:21,2023-01-03 04:31:34,2023-01-04 04:31:12,2023-01-05 04:31:16,2023-01-06 04:31:58,2023-01-07 04:31:23,2023-01-08 04:32:04,2023-01-09 04:31:38,2023-01-10 04:31:33,2023-01-11 04:31:12,...,2022-09-12 04:32:39,2022-09-13 04:33:41,2022-09-14 04:34:13,2022-09-15 04:33:33,2022-09-16 04:32:44,2022-09-17 04:32:41,2022-09-18 04:33:05,2022-09-19 04:33:01,2022-09-20 04:33:10,2022-09-21 04:33:22
Lat,32.3182,32.3182,32.3182,32.3182,32.3182,32.3182,32.3182,32.3182,32.3182,32.3182,...,42.756,42.756,42.756,42.756,42.756,42.756,42.756,42.756,42.756,42.756
Long_,-86.9023,-86.9023,-86.9023,-86.9023,-86.9023,-86.9023,-86.9023,-86.9023,-86.9023,-86.9023,...,-107.3025,-107.3025,-107.3025,-107.3025,-107.3025,-107.3025,-107.3025,-107.3025,-107.3025,-107.3025
Confirmed,1568934,1568934,1568934,1587224,1587224,1587224,1587224,1587224,1587224,1587224,...,175290,175290,175746,175746,175746,175746,175746,175746,175746,176256
Deaths,20737,20737,20737,20776,20776,20776,20776,20776,20776,20776,...,1884,1884,1888,1888,1888,1888,1888,1888,1888,1891
Recovered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Active,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FIPS,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,56.0,56.0,56.0,56.0,56.0,56.0,56.0,56.0,56.0,56.0
Incident_Rate,31998.262354,31998.262354,31998.262354,32371.285195,32371.285195,32371.285195,32371.285195,32371.285195,32371.285195,32371.285195,...,30287.217996,30287.217996,30366.007267,30366.007267,30366.007267,30366.007267,30366.007267,30366.007267,30366.007267,30454.126847
Total_Test_Results,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1503843.0,1503843.0,1503843.0,1507878.0,1507878.0,1512077.0,1512077.0,1512077.0,1512077.0,1512077.0
People_Hospitalized,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Case_Fatality_Ratio,1.321725,1.321725,1.321725,1.308952,1.308952,1.308952,1.308952,1.308952,1.308952,1.308952,...,1.07479,1.07479,1.074278,1.074278,1.074278,1.074278,1.074278,1.074278,1.074278,1.072871
UID,84000001.0,84000001.0,84000001.0,84000001.0,84000001.0,84000001.0,84000001.0,84000001.0,84000001.0,84000001.0,...,84000056.0,84000056.0,84000056.0,84000056.0,84000056.0,84000056.0,84000056.0,84000056.0,84000056.0,84000056.0
ISO3,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,...,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA
Testing_Rate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,259839.242241,259839.242241,259839.242241,260536.423624,260536.423624,261261.941499,261261.941499,261261.941499,261261.941499,261261.941499
Hospitalization_Rate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Date,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,2022-09-11 00:00:00,2022-09-12 00:00:00,2022-09-13 00:00:00,2022-09-14 00:00:00,2022-09-15 00:00:00,2022-09-16 00:00:00,2022-09-17 00:00:00,2022-09-18 00:00:00,2022-09-19 00:00:00,2022-09-20 00:00:00
People_Tested,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Mortality_Rate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df_daily['Date'].isnull().sum()

9860

Nuevo dataframe daily_act con las columnas necesarias solo

In [16]:
daily_act = ['Province_State','Confirmed','Deaths','Recovered','Active','ISO3','Date']

In [17]:
df_daily_act =df_daily[daily_act]

In [18]:
df_daily_act

       Province_State  Confirmed  Deaths  Recovered    Active ISO3       Date
0             Alabama     365747    4872   202137.0  158738.0  USA 2021-01-01
1              Alaska      47019     206     7165.0   39648.0  USA 2021-01-01
2      American Samoa          0       0        NaN       NaN  ASM 2021-01-01
3             Arizona     530267    9015    76934.0  444318.0  USA 2021-01-01
4            Arkansas     229442    3711   199247.0   26484.0  USA 2021-01-01
...               ...        ...     ...        ...       ...  ...        ...
61609        Virginia    2199302   22670        NaN       NaN  USA        NaT
61610      Washington    1883676   15038        NaN       NaN  USA        NaT
61611   West Virginia     624721    7672        NaN       NaN  USA        NaT
61612       Wisconsin    1960878   15802        NaN       NaN  USA        NaT
61613         Wyoming     182847    1958        NaN       NaN  USA        NaT

[61614 rows x 7 columns]

In [19]:
df_daily_act['Date'] = df_daily_act['Date'].dt.strftime('%d.%m.%Y')

C:\Users\fasch\AppData\Local\Temp\ipykernel_12632\1542942989.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_daily_act['Date'] = df_daily_act['Date'].dt.strftime('%d.%m.%Y')

In [20]:
df_daily_act

       Province_State  Confirmed  Deaths  Recovered    Active ISO3        Date
0             Alabama     365747    4872   202137.0  158738.0  USA  01.01.2021
1              Alaska      47019     206     7165.0   39648.0  USA  01.01.2021
2      American Samoa          0       0        NaN       NaN  ASM  01.01.2021
3             Arizona     530267    9015    76934.0  444318.0  USA  01.01.2021
4            Arkansas     229442    3711   199247.0   26484.0  USA  01.01.2021
...               ...        ...     ...        ...       ...  ...         ...
61609        Virginia    2199302   22670        NaN       NaN  USA         NaN
61610      Washington    1883676   15038        NaN       NaN  USA         NaN
61611   West Virginia     624721    7672        NaN       NaN  USA         NaN
61612       Wisconsin    1960878   15802        NaN       NaN  USA         NaN
61613         Wyoming     182847    1958        NaN       NaN  USA         NaN

[61614 rows x 7 columns]

In [23]:
#df_daily_act.to_excel("daily_report_us_final.xlsx")

In [24]:
#df_daily_act.to_csv("daily_report_us_final.csv")